### ISSUE TITLE
rspec fails in ruby 2.5.0

### ISSUE THREAD

**Issue by Yamaguchi** [Yamaguchi/noise#1]

**Comment by Yamaguchi** [comment]
Failure/Error: cipher.encrypt(nonce_to_bytes(n), ad, plaintext)
      
      OpenSSL::Cipher::CipherError:
        CTRL_NOT_IMPLEMENTED
      # ./lib/noise/functions/cipher/aes_gcm.rb:12:in `encrypt'
      # ./lib/noise/state/cipher_state.rb:36:in `encrypt_with_ad'
      # ./lib/noise/state/symmetric_state.rb:54:in `encrypt_and_hash'
      # ./lib/noise/state/handshake_state.rb:69:in `block in write_message'
      # ./lib/noise/state/handshake_state.rb:60:in `each'
      # ./lib/noise/state/handshake_state.rb:60:in `write_message'
      # ./lib/noise/connection.rb:63:in `write_message'

**Comment by Yamaguchi** [comment]
```
$ openssl version
LibreSSL 2.6.4
```
