### ISSUE TITLE
Specs failed in Ubuntu

### ISSUE THREAD

**Issue by Yamaguchi** [Yamaguchi/noise#2]
```
1) Noise::Functions::Cipher::ChaChaPoly#encrypt 
     Failure/Error: @cipher = RbNaCl::AEAD::ChaCha20Poly1305IETF.new(String.new(k).force_encoding('ASCII-8BIT'))
     
     RbNaCl::LengthError:
       Secret key was 32 bytes (Expected 0)
     # ./lib/noise/functions/cipher/cha_cha_poly.rb:8:in `new'
     # ./lib/noise/functions/cipher/cha_cha_poly.rb:8:in `encrypt'
     # ./spec/noise/functions/cipher/cha_cha_poly_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/noise/functions/cipher/cha_cha_poly_spec.rb:19:in `block (3 levels) in <top (required)>'

....
```

**Comment by Yamaguchi** [comment]
Using libsodium via rbnacl-libsodium gem solved the problem.
